apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia-argo
spec:
  replicas: 3
  template:
    spec:
      containers:
      - image: luksa/kubia
        name: kubia
        ports:
        - containerPort: 80
