apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    matchLabels:
      run: argo-kubia
  template:
    spec:
      containers:
      - image: luksa/kubia
        name: kubia
        ports:
        - containerPort: 80
